url: 'https://joseryzmal.dev'
baseurl: ''
title: 'joseryzmal.dev'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - package.json
  - tailwind.config.js
  - yarn.lock
  - assets/css/tailwind.css
