url: 'https://joseryzmal.dev'
baseurl: ''
title: 'joseryzmal.dev'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "joseryzmal.dev"

exclude:
  - package.json
  - tailwind.config.js
  - yarn.lock
  - assets/css/tailwind.css

collections:
  work_experiences:
    output: false
    order:
      - kickbooster.md
      - tactica.md
      - victoire_multimedia.md
      - freelance.md
