domain: joseryzmal.dev
url: 'https://joseryzmal.dev'
baseurl: ''
title: 'joseryzmal.dev'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "joseryzmal.dev"

exclude:
  - package.json
  - tailwind.config.js
  - yarn.lock
  - assets/css/tailwind.css
  - node_modules

collections:
  work_experiences:
    sort_by: index
