url: 'https://joseryzmal.dev'
baseurl: ''
title: 'joseryzmal.dev'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
